### ISSUE TITLE
Lack of Myanmar

### ISSUE THREAD

**Issue by Ascaris-Equi** [sonnylau98/immigrant-wiki#2]
Myanmar is a member of the Association of Southeast Asian Nations.
One of the founding countries of Myanmar, Myanmar is a multi-ethnic and multi-cultural emerging economic country.
Tourism is the third largest source of foreign exchange earnings, and the physical manufacturing industry is also developing rapidly! Immigrants to Myanmar have numerous business opportunities to choose from and invest in.
Myanmar has summer all year round, with a warm climate and abundant sunshine. The year-round temperature ranges from 21 to 32 degrees Celsius.
With its **rich products and effective economic regulation** by the government, the cost of living is one of the lowest in Asia, making it very suitable for living.

**Comment by sonnylau98** [comment]
မဖြစ်နိုင်ပါ
